### ISSUE TITLE
Build fails on new code base with EFIDROID_CHIPVENDOR not defined

### ISSUE THREAD

**Issue by ghost** [lukss12/efidroid_device_lge_hammerhead#3]
Have you tried building a newer version? It looks like there is some problem with environment:
/efidroid/uefi/edk2packages/EFIDroidPkg/EFIDroidPkg.dsc(283): error 3000: EFIDROID_CHIPVENDOR not defined

Thanks!

**Comment by thefat32** [comment]
This repo is to build EFIDroid prior to the rewrite, you can get more info about the rewrite and newer versions in efidroid.slack.com
